[tool.poetry]
name = "repl_python3_Barbara-1"
version = "0.1.0"
description = ""
authors = ["turnip123 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
discord = "^1.7.3"
discord-components = "^1.1.4"
aiofiles = "^0.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
