[tool.poetry]
name = "barbara-backend-dev"
version = "3.0.0A34"
description = "This is the experimental version of Barbara. Development of Barbara will stop for the time being after Barbara 3.0.0 is released."
authors = ["turnip123 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
discord-components = "^1.1.4"
PyNaCl = "^1.4.0"
aiohttp = "^3.7.4"
yarl = "^1.6.3"
discord = "^1.7.3"
utils = "^1.0.1"
humanize = "^3.11.0"
urllib3 = "^1.26.6"
appdirs = "^1.4.4"
pyppeteer-stealth = "^2.7.3"
pyppeteer = "^0.2.6"
console = "^0.9907"
psutil = "^5.8.0"
pandas = "^1.3.2"
pymediawiki = "^0.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
