[tool.poetry]
name = "barbara-backend-dev"
version = "0.1.0"
description = ""
authors = ["turnip123 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
discord-components = "^1.1.4"
PyNaCl = "^1.4.0"
aiohttp = "^3.7.4"
yarl = "^1.6.3"
discord = "^1.7.3"
utils = "^1.0.1"
humanize = "^3.11.0"
wikipedia = "^1.4.0"
pyppeteer = "^0.2.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
